# Generated by Django 2.1.5 on 2019-02-17 02:32

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=25)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed')], max_length=25)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('dhm', 'dhm'), ('other', 'Other')], default='other', max_length=255)),
                ('description', models.TextField()),
                ('verified', models.BooleanField(default=False)),
                ('expire_on', models.DateTimeField(blank=True, default=None, null=True)),
                ('polygon', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, default=None, null=True, srid=4326)),
                ('event', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.Event')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
