# Generated by Django 2.1.5 on 2019-02-17 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hazard', '0001_initial'),
        ('alert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='hazard',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hazard.Hazard'),
        ),
        migrations.AddField(
            model_name='activity',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alert.Alert'),
        ),
    ]
