# Generated by Django 2.1.5 on 2019-02-19 07:31

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Earthquake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('magnitude', models.FloatField()),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('event_on', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
