FROM python:3-alpine

ENV PYTHONUNBUFFERED 1
RUN mkdir -p /code/docker
WORKDIR /code

RUN \
  apk add --no-cache \
  --repository http://dl-cdn.alpinelinux.org/alpine/edge/main \
  --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing \
  gcc \
  musl-dev \
  postgresql-dev \
  openssl \
  gdal-dev \
  geos-dev \
  proj4-dev

ENTRYPOINT /code/docker/docker-entrypoint.sh
