# Generated by Django 2.1.5 on 2019-02-17 02:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('status', models.CharField(choices=[('relocated', 'Relocated'), ('evacuated', 'Evacuated')], max_length=25)),
                ('below_poverty', models.BooleanField(blank=True, default=None, null=True)),
                ('count', models.PositiveIntegerField(default=1)),
                ('phone_number', models.CharField(blank=True, default=None, max_length=25, null=True)),
            ],
            options={
                'verbose_name_plural': 'families',
            },
        ),
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('status', models.CharField(choices=[('destroyed', 'Destroyed'), ('affected', 'Affected')], max_length=25)),
                ('equipment_value', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('infrastructure_value', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('beneficiary_owner', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('service_disrupted', models.BooleanField(blank=True, default=None, max_length=255, null=True)),
                ('count', models.PositiveIntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InfrastructureType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Livestock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('status', models.CharField(choices=[('destroyed', 'Destroyed'), ('affected', 'Affected')], max_length=25)),
                ('count', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LivestockType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('estimated_loss', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('detail', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name_plural': 'losses',
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('dead', 'Dead'), ('missing', 'Missing'), ('injured', 'Injured'), ('affected', 'Affected')], max_length=25)),
                ('name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('age', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], default=None, max_length=25, null=True)),
                ('below_poverty', models.BooleanField(blank=True, default=None, null=True)),
                ('disabled', models.BooleanField(blank=True, default=None, null=True)),
                ('count', models.PositiveIntegerField(default=1)),
                ('loss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peoples', to='loss.Loss')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='livestock',
            name='loss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livestocks', to='loss.Loss'),
        ),
        migrations.AddField(
            model_name='livestock',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='livestocks', to='loss.InfrastructureType'),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='loss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infrastructures', to='loss.Loss'),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='infrastructures', to='loss.InfrastructureType'),
        ),
        migrations.AddField(
            model_name='family',
            name='loss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='families', to='loss.Loss'),
        ),
    ]
