# Generated by Django 2.1.5 on 2019-02-17 02:32

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hazard', '0001_initial'),
        ('event', '0001_initial'),
        ('loss', '0001_initial'),
        ('federal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('cause', models.TextField(blank=True, default=None, null=True)),
                ('inducer', models.CharField(blank=True, choices=[('artificial', 'Artificial'), ('natural', 'Natural')], default=None, max_length=25, null=True)),
                ('severity', models.CharField(blank=True, choices=[('minor', 'Minor'), ('major', 'Major'), ('catastrophic', 'catastrophic')], default=None, max_length=25, null=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, default=None, null=True, srid=4326)),
                ('polygon', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, default=None, null=True, srid=4326)),
                ('incident_on', models.DateTimeField(blank=True, default=None, null=True)),
                ('street_address', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('detail', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
                ('event', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.Event')),
                ('hazard', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hazard.Hazard')),
                ('loss', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loss.Loss')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IncidentSource',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='incident',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='incident.IncidentSource'),
        ),
        migrations.AddField(
            model_name='incident',
            name='wards',
            field=models.ManyToManyField(related_name='incidents', to='federal.Ward'),
        ),
    ]
