# Generated by Django 2.1.5 on 2019-02-19 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
