# Generated by Django 2.1.5 on 2019-02-21 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.Resource')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('resources.resource',),
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.Resource')),
                ('cbs_code', models.IntegerField(blank=True, default=None, null=True)),
                ('channel', models.CharField(choices=[('blb', 'Branchless Banking'), ('branch', 'Branch'), ('atm', 'ATM')], max_length=25)),
                ('population', models.PositiveIntegerField()),
                ('acces_points_count', models.PositiveIntegerField(default=1)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('resources.resource',),
        ),
        migrations.CreateModel(
            name='Governance',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.Resource')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('resources.resource',),
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.Resource')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('resources.resource',),
        ),
        migrations.CreateModel(
            name='Tourism',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.Resource')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('resources.resource',),
        ),
        migrations.RenameField(
            model_name='education',
            old_name='no_of_classrooms',
            new_name='classroom_count',
        ),
        migrations.RenameField(
            model_name='health',
            old_name='no_of_beds',
            new_name='bed_count',
        ),
    ]
